### ISSUE TITLE
Lost Segments

### ISSUE THREAD

**Issue by Portree-Kid** [Portree-Kid/flightgear-airports#10]
Under unclear circumstances Segments can get lost. 

![image](https://user-images.githubusercontent.com/999932/82980776-8c1b8980-9fea-11ea-947b-6ca260d5a00b.png)

**Comment by BecOzIcan** [comment]
I can reproduce

**Comment by BecOzIcan** [comment]
1. Draw a di-directional NOT STARTING on an existing node 
![image](https://user-images.githubusercontent.com/49523106/82991431-0545cb80-a041-11ea-831e-5e21f3c187e2.png)

**Comment by BecOzIcan** [comment]
2. end it on an existing node. Double click to connect. Drag to prove they are connected 
![image](https://user-images.githubusercontent.com/49523106/82991544-2efef280-a041-11ea-97c6-10a77e6d2ea6.png)

**Comment by BecOzIcan** [comment]
Select the first node drawn and delete it 
![image](https://user-images.githubusercontent.com/49523106/82991649-5786ec80-a041-11ea-819f-d797a2e42949.png)

**Comment by BecOzIcan** [comment]
The entire path is deleted (which is a bug in itself 
![image](https://user-images.githubusercontent.com/49523106/82991688-69688f80-a041-11ea-857c-169a8adc4a83.png)

**Comment by BecOzIcan** [comment]
Click an Drag teh node where you new path was initially ending ..... TADA ! path os broken at this point 
![image](https://user-images.githubusercontent.com/49523106/82991793-9157f300-a041-11ea-8a5e-cd12c6ff04e4.png)

**Comment by Portree-Kid** [comment]
Wrong but not the same issue. The Screengrab shows it post save and this issue fixes it self with save.
