### ISSUE TITLE
0.0.26: number="undefined" appears in the XML for empty gate numbers

### ISSUE THREAD

**Issue by sfrsfrsfr** [Portree-Kid/flightgear-airports#101]
Sometimes gates are named e.g. B94A. In that case i set this as the name and leave the number field empty.
The exported XML then contains number="undefined". Instead it should possibly be number="" or not be output at all.
Might be worth to check the FG sources how name/number fields are treated.

**Comment by Portree-Kid** [comment]
Fixed 0.0.27
