### ISSUE TITLE
v 0.0.27 Clicking on Parking List Entry takes me to another airport 

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#109]
Navigate to RJTT Tokyo Haneda (merged recently)
> Map Shown Ok
Click on Properties
> Frequencies Ok 
> Parking List shown Ok
> Airlines List Ok 

Issue 1 : Element shown by Default in Top panel (nothing clicked on so far) is a parking spot in Torino Italia

![image](https://user-images.githubusercontent.com/49523106/103633330-b3cbca80-4f99-11eb-9dd2-0e7b55a9d5a4.png)

Issue 2 : 

Clicking on a Parking spot on the list (from the naming I know they are RJTT ones), I am taken to the map of Torino Airport (gate_108)

![image](https://user-images.githubusercontent.com/49523106/103633378-c0e8b980-4f99-11eb-9e3e-1478a360712b.png)

**Comment by Portree-Kid** [comment]
Fixed
