### ISSUE TITLE
segments disappear after repeated splitting

### ISSUE THREAD

**Issue by sfrsfrsfr** [Portree-Kid/flightgear-airports#113]
hi, 

i can't give a precise procedure for replicating it but it happens very often/always when editing segments/nodes.
Often i need to add several nodes at a segment. To do that i click on the 'translucent' center node to split a segment in two.
I'm not able to do that repeatedly. If i do it and drag one of the new nodes usually part of the segment disappears.
Thus i resorted to : Split -> Save -> Edit -> Split... which takes considerable longer. Maybe whatever reorg routine runs during Save should also be called after a Split?

[Sample image](https://i.imgur.com/dELjmv8.png) with 0.0.27

**Comment by Portree-Kid** [comment]
Currently not reproducible. Please provide Video of workflow.

**Comment by sfrsfrsfr** [comment]
Sample video on [youtube](https://youtu.be/4IjauRFWM6k)
Unfortunatelly the mouse cursor wasn't recorded. What i did was splitting the segment two times and then dragged the 2nd newly created node.

Groundnet file:
https://pastebin.com/KZJiKx1x

**Comment by Portree-Kid** [comment]
Reproducible: The problem are short segments. I'll try and find a way to block splitting them. You split as long as you like if you continue pulling the segments apart.

**Comment by Portree-Kid** [comment]
Fixed with a hack
