### ISSUE TITLE
Feature Request (GUI): It must be possible to save without leaving the edit mode.

### ISSUE THREAD

**Issue by sfrsfrsfr** [Portree-Kid/flightgear-airports#114]
when editing a groundnet one very often needs to save. But edit mode is off after saving so you need to click 'Edit' again.
Thus the white 'menu area' on the left usually stays popped open taking up a considerable amount of screen space. Especially when working with several windows open (browser with Satellite images and/or a PDF viewer for airport charts).

what would others think of moving the Edit button to the graphical area? e.g. below the 'Layers' button

**Comment by Portree-Kid** [comment]
It was specifically moved as it is in the context of an airport. @BecOzIcan can you please comment.

**Comment by BecOzIcan** [comment]
Ho both 

From the functions hierarchy point of view "Edit" as in 'I want to change something" should live on the left hand side with the rest of the top level activities (Upload, Scrap, Check), hence my previous recomendation ; 
A user may want to use EDIT something else than an element on the map eg comms frequency.

From this logic, SAVE should live in the same space but it is convenient to have it on the map to do intermediate backup as described in Stefan's request. 

I would suggest to fix the other side of the problem ie saving as you go should not kick you out of EDIT mode. 
(Of course we should still be able to calculate a delta from the last save to warn the user, trying to exit without saving).

Hope this makes sense

Cheers
Ian

**Comment by BecOzIcan** [comment]
@Stefan : you can collapse the left hand side menu when updating the groundnet and get the map in full screen, use the triangle on the top right of the pannel

**Comment by sfrsfrsfr** [comment]
not leaving EDIT mode on save is probably the propper solution. the location of the EDIT button is then fine with me.
@BecOzIcan that is clear, but atm one needs to reopen it very often to re-enter EDIT mode.

**Comment by BecOzIcan** [comment]
I wasn't sure you know about the panel (although it visually is obvious). Yes, having to expand the panel just to click edit is bad UX in the context of editing/saving a groundnet over long periods of time.  Hopefully Keith can set up this "save but continue to edit"  behavior

**Comment by Portree-Kid** [comment]
Is it Ok if I rename the Requirement to "It must be possible to save without leaving the edit mode."

**Comment by sfrsfrsfr** [comment]
yes of course, go ahead. that will also remove the need to frequently push the Edit button.

**Comment by BecOzIcan** [comment]
Absolutely

Yves

________________________________

**Comment by BecOzIcan** [comment]
Functionally and visually Spot On in v0.0.29
Versioning the backups and linking them to undo is a super nice touch as well.
Well Done!
