### ISSUE TITLE
V 0.027 Cannot type in ParkPos Nose wheel LAT LON

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#115]
1. ParkPos Selected 
2. "Calculate Centre" Selected in LHS Panel

Expected : 
- I can type in a LAT LON with my num pad
- Parkpos Center Coordinates will be calculated
- Parkpos Icon will be re-positioned on the map according to its calculated center coordinates

Observed : LAT LON numbers cannot be entered, cursor seems stuck at the end of coordinates string, typing number change randomly the content in various positions in the string. On image below I am trying to enter 39.441778, -83.782879

Nota: Occurs only when entering nose-wheel coordinates; Ok when entering center coordinates. Also ok when changing lat lon of a node 

UX Suggestion: 
- Split LAT and LON into two different boxes
- TAB to navigate from one to the other (or click on the one to activate and type)
- (Option) Validate content on exiting the box (Tab out of Click out) : LAT is between -90 and +90, LON is between -180 and +180
- Reflect Content on Map on click out or tab out only, not dynamically as I type
- [ESC] while typing Return box content to initial value (because what I type as not been validated yet)

![image](https://user-images.githubusercontent.com/49523106/104092502-82743700-52d8-11eb-8257-96a19a855e72.png)

**Comment by sfrsfrsfr** [comment]
fyi, using the mouse marking the current coordinates and then pasting a previously copied set of coordinates works.

**Comment by BecOzIcan** [comment]
Clever workaround ! Just tried and it works. Thanks for that. Not ideal though as it means I need to pre-format my INS data in a separate document (to be able to copy) ahead of building the groundnet.

**Comment by Portree-Kid** [comment]
I was setting the positions via grab from document, so I didn't realise. But fixed in 0.0.28

**Comment by BecOzIcan** [comment]
Checked in v0.028 and smooth as silk! Thank you
