### ISSUE TITLE
PARKPOS Properties : None is NOT a valid Type 

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#12]
We should not offer the none option in this list

![image](https://user-images.githubusercontent.com/49523106/83000565-e26de400-a04d-11ea-8fe2-dee5cf04255b.png)

**Comment by Portree-Kid** [comment]
Fixed

**Comment by BecOzIcan** [comment]
Still here in 0.13. 
3 distinct issues  
None is ParkPos value by default
None can be selected in ParkPos Combo 
None  and is not picked up by verification as a problem
