### ISSUE TITLE
v0.0.28 Beacon Icon does not scale on zoom out

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#120]
Somehow Similar to issue with THR in v0.027

![image](https://user-images.githubusercontent.com/49523106/104733812-5bfc4300-5793-11eb-88ac-9031c3d70e7e.png)

![image](https://user-images.githubusercontent.com/49523106/104733926-8bab4b00-5793-11eb-8461-946ebf4a5217.png)

**Comment by Portree-Kid** [comment]
Can you please check if it's one from a previously opened airport. I can see a second one and they should never be visible at that zoom anyway.

**Comment by BecOzIcan** [comment]
Yes I had visited both during this "session" the most northern one OBBI I actually edited. the Southern one OMAA I only soomed in. 

I will try to reproduce so I can provide some steps

**Comment by BecOzIcan** [comment]
1. OPEN FGA
2. Magnifying glass icon to lookup an airport 
3. Type LFPG > Foudn in list
4. Click on link > Taken to airport in max zoom in, centered on Beacon 

![image](https://user-images.githubusercontent.com/49523106/104735494-c31af700-5795-11eb-8f19-6c099d925d2b.png)

6. Search side panel still open, lookup LIRF and click on result > Map re centered onto Rome's Beacon 

![image](https://user-images.githubusercontent.com/49523106/104735617-e776d380-5795-11eb-8a84-f7e76f136e08.png)

Click the map Icon for world level then zoom even further out with mouse scroll (middle button 
Rome Beacon not shown but LFPG and OBBI (edited in last session are here in your face

![image](https://user-images.githubusercontent.com/49523106/104735721-0e350a00-5796-11eb-9d43-87e57241dea0.png)

**Comment by BecOzIcan** [comment]
Lookinup NTAA Faa Papeete, zoomin in at max level the tower icon is large but it scales back nicely when zooming out, still in the same search / go / view only session 

![image](https://user-images.githubusercontent.com/49523106/104736464-1477b600-5797-11eb-8e82-b6c4391c5e15.png)

![image](https://user-images.githubusercontent.com/49523106/104736481-1f324b00-5797-11eb-95f7-a93752f66c2e.png)

**Comment by BecOzIcan** [comment]
WSSS Singapore .... 
![image](https://user-images.githubusercontent.com/49523106/104736716-79cba700-5797-11eb-90be-63cc7a8e64ea.png)

I ll stop here ...

**Comment by BecOzIcan** [comment]
Went back to Bahrain OBBI and switched to edit mode, looks like I have more than one tower icon on top of each others and definitely too big

![image](https://user-images.githubusercontent.com/49523106/104737014-d3cc6c80-5797-11eb-89f1-8598b7bfb03d.png)

**Comment by BecOzIcan** [comment]
Switching Tower layer OFF takes out only the top one 

![image](https://user-images.githubusercontent.com/49523106/104737105-f068a480-5797-11eb-9675-56bd268c6bd6.png)

**Comment by Portree-Kid** [comment]
Ah Ok. That was my hunch. BTW that's the location of the tower (icao.twr.xml) alternative svg always welcome

**Comment by BecOzIcan** [comment]
:-) 
Definitely happy to provide that. I ll put one together over the weekend.

**Comment by BecOzIcan** [comment]
Options: 

![image](https://user-images.githubusercontent.com/49523106/104828764-d971a180-58c0-11eb-8eb4-dcaaae2cf8f1.png)
