### ISSUE TITLE
v0.0.29 Nosewheel coordinates no longer shown & broken "Calculate" Toggle UI

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#126]
Expected (previous) behavior: Toggle between calculate NoseWheel & Calculate Centre BUTTONS would

1. Grey out the calculated box (and show value currently persisted in XML) 
2. Unlock the Box for entering the alternative value (Centre if Nosewheel calculated & vice versa) 

Observed : 
- Whatever calculate button is pressed. the centre values are shown and the nosewheel box shows "please input"
- Greying is consistent with button selection but not the box content (nosewheel current values never shown)

![image](https://user-images.githubusercontent.com/49523106/106354385-99410300-6345-11eb-9eed-ced31f63e31a.png)

**Comment by Portree-Kid** [comment]
Fixed in 0.0.30
