### ISSUE TITLE
v0.0.30 : Check Result : Crashed 

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#128]
Open OMAA 

Run Check

![image](https://user-images.githubusercontent.com/49523106/108848147-bb702d00-7634-11eb-8285-93e32888a154.png)

check.js:44 Crashed
(anonymous) @ check.js:44
Promise.catch (async)
onmessage @ check.js:43
check.js:45 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at check.js:237
    at Array.map (<anonymous>)
    at check.js:233
    at new Promise (<anonymous>)
    at checkGroundnet (check.js:57)
    at onmessage (check.js:38)

**Comment by Portree-Kid** [comment]
Fixed in 0.31
