### ISSUE TITLE
v0.0.31 CAnnot Vary Heading more than 0.2 deg using Using +/- button

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#130]
LFPG
Fedex Apron
Multiple Positions. Trying to increase decrease heading with button, cannot change more than +/- 0.2 degrees
Manually typing a new heading value works fine 

![image](https://user-images.githubusercontent.com/49523106/117464950-823d2d00-af94-11eb-9491-5bfb6128aadd.png)

**Comment by Portree-Kid** [comment]
Fixed in 0.33
