### ISSUE TITLE
V.0.0.31 Scanning Can't be Triggered if Debugger is ON 

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#133]
Clicking on Scan Traffic File does not seem to trigger the re-sync anymore; No Message, No Progress bar. Button remains active. 

![image](https://user-images.githubusercontent.com/49523106/118436182-b1396880-b723-11eb-92d9-1e67d85de3b0.png)

**Comment by BecOzIcan** [comment]
Found that Issue occurs only when Debugger Option is ON 

With Scan Logging OFF, refresh of Traffic, Groundnets and APT runs smoothly.

Maybe as an Improvement, the 3 buttons should be greyed out / inactive on the Scanning Tab when debugger is ON ?   

![image](https://user-images.githubusercontent.com/49523106/120057670-4f182600-c088-11eb-982c-9f4d1ad31d19.png)

**Comment by Portree-Kid** [comment]
I hate windows 10. That will be the fact that you can’t write everywhere as an app.

**Comment by Portree-Kid** [comment]
Fixed in 0.33
