### ISSUE TITLE
Wrong Pushback Holding Point ID persisted 

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#134]
Expected : Upon File check, FGA should

- Persist in each Parking/Gate record, the ID of the Pushback Holding Point for this gate (final node on which the aircraft leaving the gate will end its pushback and start rolling forward).

`<parkingList>
    <Parking index="0"
           pushBackRoute="113"`

- Verify that each Gate does not have more than one PHP (more than one gate can share a single PHP)

Observed : 

- The value persisted in "pushBackRoute" is erroneous and systematically equal to Correct Value minus one, some sort of indent must be at play 
- AI Aircrafts no longer know where to end their pushback and then continue rolling backwards to the centre of the airport
- Issue found in v0.0.30 and v0.031 (previous versions not checked) 

Example Below at YSSY. Aircrafts leaving Gate T1-33 via pushback should end up the pushback on node 716. The groudnet generated upon check persists pushBackRoute="715"

![image](https://user-images.githubusercontent.com/49523106/119441532-9ab98f80-bd69-11eb-95b8-c25ed41f3c03.png)

**Comment by sfrsfrsfr** [comment]
i can confirm this bug. See the recently uploaded groundnet of LOWS.
FGA 0.0.26 and 0.0.27 (EDDC) seem to be ok. 0.0.28 as well i think (LIMJ)

**Comment by BecOzIcan** [comment]
Issue observed again in v0.0.32 

![image](https://user-images.githubusercontent.com/49523106/121661721-d8e3dc80-cae7-11eb-8309-b868626ba367.png)

![image](https://user-images.githubusercontent.com/49523106/121661847-fc0e8c00-cae7-11eb-90bb-ee122c4ecc47.png)

**Comment by BecOzIcan** [comment]
Something else must be at play

**Comment by BecOzIcan** [comment]
Investigating

**Comment by BecOzIcan** [comment]
Also getting duplicated Edges.

**Comment by BecOzIcan** [comment]
Duplicated Edge errors are real and not picked up by FGA Check

**Comment by BecOzIcan** [comment]
![image](https://user-images.githubusercontent.com/49523106/121663968-5577ba80-caea-11eb-8303-3fa7bc13de84.png)

**Comment by sfrsfrsfr** [comment]
see #139 . the next version will have a search function that allows one to locate duplicates

**Comment by BecOzIcan** [comment]
Awesome. Thanks for the link

**Comment by Portree-Kid** [comment]
Yes 0.33 now has a search and a check for double edges.
