### ISSUE TITLE
Add Parking Category/Radius to Properties View in simple (non-edit) mode

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#137]
Was trying to quickly check EDDE had enough Cargo gates to address a Forum question and noticed the FGA parking list does not display the gates sizes (either Category and Radius) in simple/non-edit view mode 

![image](https://user-images.githubusercontent.com/49523106/120087130-cb624600-c128-11eb-842c-51a474749f76.png)

**Comment by Portree-Kid** [comment]
Fixed even though it isn't beautiful

**Comment by BecOzIcan** [comment]
Checked and OK. Agreed not beautiful :-) We can look at shorter Aircraft description in the radius table later
