### ISSUE TITLE
Search for a specific node by ID

### ISSUE THREAD

**Issue by sfrsfrsfr** [Portree-Kid/flightgear-airports#139]
There should be an option to jump to a certain node.
Many groundnets contain duplicate nodes/edges which are hard to find (look up their coordinate, convert it to a fromat suitable for osm to display. find the same spot in fga and search for the duplicate).

While fg ignores these duplicates they should be cleaned up nonetheless.

`EDDK ground-net: skipping duplicate edge:13->179
    0.39 [WARN]:navaid     EDDK ground-net: skipping duplicate edge:179->13
    0.39 [WARN]:navaid     EDDK ground-net: skipping duplicate edge:14->180
    0.39 [WARN]:navaid     EDDK ground-net: skipping duplicate edge:180->14
    0.39 [WARN]:navaid     EDDK ground-net: skipping duplicate edge:17->183
    0.39 [WARN]:navaid     EDDK ground-net: skipping duplicate edge:183->17`

**Comment by Portree-Kid** [comment]
Will be fixed via #8 and #105

**Comment by Portree-Kid** [comment]
And on a side note. A simple load/store will remove duplicate edges and orphan nodes.

**Comment by sfrsfrsfr** [comment]
Automatic removal of duplicate edges upon save/reload doesn't work for me in 0.0.32.
While editing the groundnet of EDDK i still got the fg warnings about duplicate edges until i deleted them.

EDDG also has two duplicates (first pushback segment at Gate_12/Gate_13):
`29.27 [WARN]:navaid     EDDG ground-net: skipping duplicate edge:5->63
   29.27 [WARN]:navaid     EDDG ground-net: skipping duplicate edge:63->5
   29.27 [WARN]:navaid     EDDG ground-net: skipping duplicate edge:6->64
   29.27 [WARN]:navaid     EDDG ground-net: skipping duplicate edge:64->6
`

To replicate: Open EDDG groundnet, enter Edit mode. Then click Save (i tested Save but also Close/Save Editing) and exit/quit fga. Open fga and reload EDGG, the duplicates still exist.

**Comment by Portree-Kid** [comment]
Version 0.33 will have a check for double edges and a goto function. This fixes the finding of the double edges but not the finding of ids so this bug will stay open.

**Comment by sfrsfrsfr** [comment]
having a way to identify and fix duplicate edges is good enough for me. is there a need to be able to locate a specific id?

**Comment by Portree-Kid** [comment]
I've implement a general search. Helps you find parkings.
