### ISSUE TITLE
0.0.32: Airport search: Issue when searching by ICAO

### ISSUE THREAD

**Issue by sfrsfrsfr** [Portree-Kid/flightgear-airports#140]
the search function does not quite work as one would expect. Most of the time i 'search' for an airport by entering its ICAO code.
The search is mostly ok if only the first three letters are entered. A list of matches remains from where the wanted airport can be chosen. But it fails if i enter all four letters. First off the forth letter is not shown in the entry box. But the correct airport moves to the top of the current search results. Upon clicking on the airport name nothing happens. Also clearing the search and starting over is not possible anymore. Restaring fga at this point will actually show the desired airport.

Interestingly enough it appears to work fine when searching by names (e.g. frankfurt).

**Comment by Portree-Kid** [comment]
Fixed in 0.0.33
