### ISSUE TITLE
File Upload no longer working in Either FGA or Groundweb

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#151]
### Groundweb indicates Azure is OK, authorizes upload but runs forever 

![Image1](https://user-images.githubusercontent.com/49523106/143733939-8a679641-030b-4f34-8fa4-e32510801db8.png)
![Image2](https://user-images.githubusercontent.com/49523106/143733940-721ec44d-158d-47d1-b14a-c5e065d122ef.png)
![Image3](https://user-images.githubusercontent.com/49523106/143733942-4aeea1b5-deee-4345-8982-fccdb53d6d39.png)
![Image4](https://user-images.githubusercontent.com/49523106/143733943-2eb0f63b-59a3-4208-97f2-8bffa8ce214d.png)

### FGA does not confirm Azure is up but let the Upload start then returns an error 

![Image1](https://user-images.githubusercontent.com/49523106/143733903-14f16e70-7f51-454a-81ac-ec5464e45ba8.png)
![Image2](https://user-images.githubusercontent.com/49523106/143733904-003b18e2-b8cd-49d2-b69f-464051ef2cb3.png)
![Image3](https://user-images.githubusercontent.com/49523106/143733900-193718d5-f107-4d07-8c7a-52f91a4d7c3f.png)
![Image4](https://user-images.githubusercontent.com/49523106/143733902-1c8e1e08-ad9b-4f8b-8965-ec82e788ecc5.png)

In both cases, no PR received on https://github.com/terrasync/main/pulls

**Comment by varjatichko** [comment]
It still returns HTTP 500 for the request even after Ok returned in the json after Azure check.

![Azure](https://user-images.githubusercontent.com/58511928/143785057-54c31622-3b58-474b-94c5-75a9dcb0b36e.png)

**Comment by varjatichko** [comment]
Last two days it responds to Azure check as undefined and next json:
{"message":"Error","err":{"message":"the index is locked; this might be due to a concurrent or crashed process","errno":-14,"errorFunction":"Index.write"}}

Hope this helps to identify and fix the issue

**Comment by Portree-Kid** [comment]
Fixed

**Comment by BecOzIcan** [comment]
Verified. Back to normal. Thanks Keith
