### ISSUE TITLE
Check : No way to Pushback Holdpoint

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#16]
YSSY (Valid as per Taxidraw validation) 
Run Check in FGA
Return series of" No way to Pushback Holdpoint" errors where gate is actually connected to pushback

**Comment by BecOzIcan** [comment]
With clearer image(s). second one I dragged each node to prove it is connected. 

![No way to pushback holding point](https://user-images.githubusercontent.com/49523106/84655321-1b65ee00-af54-11ea-94a9-2207f6dd21bd.png)


![No way to pushback holding point proof connect](https://user-images.githubusercontent.com/49523106/84655282-0c7f3b80-af54-11ea-923c-59e90aaae981.png)

**Comment by Portree-Kid** [comment]
Completely wrong bug. The index was seemingly pointing to the wrong parking. 
![image](https://user-images.githubusercontent.com/999932/84654762-0b2c1f80-af10-11ea-8f0c-438d4b1d5c6f.png)
![image](https://user-images.githubusercontent.com/999932/84655425-38c59880-af11-11ea-98b5-4e2f5993eb1f.png)
