### ISSUE TITLE
Check : No way from Runway to Each parking

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#17]
Airport YSSY 

All routes between ParkPos and Runway nodes are valid as per Taxidraw. Rejected by FGA. Can't isolate the 'pair' of points failing as map is too busy when zooming out. 

Screenshot below also shows one error generated for each node On Runway. Testing (and error message reporting) against the last node on the route/on runway should be enough., the rest of the route consistency is tested separately anyway.

![No way from runway to each parking](https://user-images.githubusercontent.com/49523106/84655762-e1e1b280-af54-11ea-90ae-b74262a119d0.png)

**Comment by Portree-Kid** [comment]
Part one Fixed in 0.0.13

**Comment by Portree-Kid** [comment]
![image](https://user-images.githubusercontent.com/999932/86398846-8b8ba800-bca6-11ea-8ea6-250d71a86ad7.png)
More complicated than expected

**Comment by Portree-Kid** [comment]
Fixed in 0.0.16
