### ISSUE TITLE
Nodes & ParkPos Precision and UI

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#18]
Node LAT / LON can be manually typed with 6 decimals 

![image](https://user-images.githubusercontent.com/49523106/85216750-cf8bcc80-b3cb-11ea-934a-1432d4b3d1c8.png)

Showed Saved as 6 decimals 
![image](https://user-images.githubusercontent.com/49523106/85216760-eaf6d780-b3cb-11ea-8ba3-ba8d42edcc42.png)

On RE-EDIT. Values are rounded to 5 an node moved
![image](https://user-images.githubusercontent.com/49523106/85216770-095cd300-b3cc-11ea-9b54-aabe97676b9a.png)

EXPECTED : Nodes and ParkPos have 6 decimals precision 
EXPECTED : Dragging node on map updates dynamically LAT LON in Properties

ALSO : Same issue with ParkPos : 

Position Shown on saving 
![image](https://user-images.githubusercontent.com/49523106/85217006-04e5e980-b3cf-11ea-8544-40bf6eccf787.png)

Postion shown on re-edit (shifted) 
![image](https://user-images.githubusercontent.com/49523106/85217009-1af3aa00-b3cf-11ea-8ed2-de76ddd8933d.png)

**Comment by Portree-Kid** [comment]
Fixed in 0.0.16
