### ISSUE TITLE
PARKPOS # saved as number instead of Text

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#19]
Assign a 2 digits number to a Parkpos with first digit is 0 
Save 

![image](https://user-images.githubusercontent.com/49523106/85216873-61480980-b3cd-11ea-81d4-542bcc8de384.png)

RE EDIT 

![image](https://user-images.githubusercontent.com/49523106/85216882-74f37000-b3cd-11ea-8177-b33ff4c7b584.png)

OBSERVED : 
If Gate # is number : leading zero removed
If Gate # is text : content saved as is  
EXPECTED : Gate Number values saved as is (as Text) including leading zeros

**Comment by Portree-Kid** [comment]
Fixed in 0.0.15
