### ISSUE TITLE
DRAW Forward Taxiline. Not rendered unless re-selected, Can't un-select

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#2]
Entry conditions : 2 existing separate nodes

Tool Draw Forward Line 
Click on first node
Click on second node
A Segment is created between the two nodes
Re click on second node
Draw tool deactivated 
Click on a third node (go away)

BUG 1 : Line drawn does not reflect it is unidirectional (no red arrows) 

Click on the line drawn 

Lines is red (Selected) 
Line shows red arrows indicating unidirectional 

Click other element (go away)
Other Elements turned red (selected) 

BUG 2 : Drawn line is NOT unselected and remains red

**Comment by Portree-Kid** [comment]
Fixed
