### ISSUE TITLE
UI - two or more scans at the same time use the same progress bar location 

### ISSUE THREAD

**Issue by wkitty42** [Portree-Kid/flightgear-airports#24]
you can run more than one scan at a time...

problem: there is only one progress bar location at the top under the blue title field... each running scan updates that location with its progress bar... that section of the UI flips back and forth between each progress bar...

solution: perhaps put a scan-specific progress bar with each scan button OR even better, make each scan button the progress bar for that scan...

**Comment by Portree-Kid** [comment]
Fixed in 0.0.17
