### ISSUE TITLE
MacOS file path

### ISSUE THREAD

**Issue by Honu4** [Portree-Kid/flightgear-airports#29]
MacOS Flightgear directory path `/Applications/Flightgear/Contents/Resources` needs to be `/Applications/Flightgear.app/Contents/Resources` for scan to work. Path is not editable from Settings dialogue. Current workaround is to remove ".app" from Flightgear contents package

**Comment by Portree-Kid** [comment]
How do you select that? 
![image](https://user-images.githubusercontent.com/999932/87218084-d913af00-c34f-11ea-84ae-de00ea58368d.png)
Can you supply some screenshots?

**Comment by Honu4** [comment]
I have to remove the ".app" extension from the Mac program package. Then the folder structure is accessible to the program.
<img width="667" alt="Screen Shot 2020-07-10 at 9 08 07 PM" src="https://user-images.githubusercontent.com/67807217/87218773-873c3c00-c2f1-11ea-99b5-db3561b183c1.png">

**Comment by Portree-Kid** [comment]
Solved in 0.0.25 
Now FGData must be set directly

**Comment by Honu4** [comment]
I donʻt know if this was ever fixed, but I still need to remove the .app suffix from the Flightgear application package to access Flightgear data folders as was addressed in original post.

**Comment by Honu4** [comment]
Okay. I use [this tip for the A320 MCDU.html](https://github.com/legoboyvdlp/A320-family/issues/221#issuecomment-801054266) addon to fix my directories issue. I think I'm good now.

Thanks
