### ISSUE TITLE
DATA: No taxiway/pushback rendered at LFPG

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#3]
Only Parkpos and Pushback holding points shown. Issue does not happen at other airports. Check repo with taxidraw and taxilines are in there. Properties panel counts 1404 nodes but none shown

**Comment by Portree-Kid** [comment]
Bug in a coordinate parsing lib 

N49 0.000 E02 33.314 doesn't parse. 

https://github.com/ianengelbrecht/geo-coordinates-parser/issues/1

adding hack :-( for the meantime

**Comment by BecOzIcan** [comment]
French bashing in disguise ?

Thanks for checking 🙂

________________________________

**Comment by Portree-Kid** [comment]
Promptly resolved by @ianengelbrecht upstream
