### ISSUE TITLE
Zooming in/out resets the "Hide APT" option

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#30]
**Both View & Edit modes** 
Go to an airport
Toggle Hide APT 
> APT Data hidden from map 
Zoom in or out 
> APT Data re-appears on map 

UI: Can't deduct the Enabled / Disabled status of Hide APT icon from look & feel (same in both state?). Could use some visual treatment to help differentiate states

**Comment by Portree-Kid** [comment]
Fixed in 0.0.18
