### ISSUE TITLE
Node "Selected" Red Colour toggled off if position varied (Type or Drag) 

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#31]
Click on a node 
> Node turns Red
Drag node with Mouse to a different location 
> Node turns White (x) 
> Node still selected (LAT LON update dynamically in Properties if dragged further (/)

Click on a node 
> Node turns Red
Change (type in) LAT LON in Properties Panel  
> Node turns White (x) 
> Node Moves on map along LAT LON typed in properties (/) 

Confusing to user where multiple nodes sit next to each other, which one is under edit 

![image](https://user-images.githubusercontent.com/49523106/86524578-98cfaf00-bebf-11ea-82d3-25c24fafc628.png)

**Comment by Portree-Kid** [comment]
Fiexed in 0.0.18
