### ISSUE TITLE
0.0.16 not detecting any errors

### ISSUE THREAD

**Issue by gooneybird47** [Portree-Kid/flightgear-airports#32]
Version 0.0.16 is not detecting any errors,  having to use Taxidraw for no route found etc.
Tried putting deliberate errors in and none were found.

Have attached the file I'm currently working on.

[GVAC.groundnet.new.zip](https://github.com/Portree-Kid/flightgear-airports/files/4875480/GVAC.groundnet.new.zip)

**Comment by wkitty42** [comment]
FWIW: it has caught numerous ones of mine i've made at KCLT and KCHS... but they're pretty basic ground nets, too...

**Comment by gooneybird47** [comment]
I've reinstalled and rescanned this morning and it's now working again so I'm going to close this. 
Sorry about the extra noise I should have tried that first.

**Comment by wkitty42** [comment]
just for additional info... i dunno about reinstalling... i'm using the appimage for 0.0.16 on my linux...
