### ISSUE TITLE
missing selected parking restrictions when opening ground net subsequent times

### ISSUE THREAD

**Issue by wkitty42** [Portree-Kid/flightgear-airports#33]
i just created KCHS yesterday... today i added restrictions to the parking, saved, and exported... a few minutes later, i opened the appimage (0.0.16) again still at KCHS... i went into edit mode to look at the parking again and the restrictions do not appear... clicking on the dropdown shows none of the previously selected airlines as selected...

looking in the existing exported copy of KCHS, i see the restrictions are properly listed...

opening the appimage (0.0.16) again, entering edit mode, selecting parking A2, see no restrictions, save, export, look at exported ground net and the restrictions are properly listed still...

**Comment by Portree-Kid** [comment]
Fixed in 0.0.18
