### ISSUE TITLE
Allow entry of airline codes with no traffic (yet)

### ISSUE THREAD

**Issue by LGBudd** [Portree-Kid/flightgear-airports#39]
Doing KPHL I found that fg-airports displays those airline codes with traffic currently in FlightGear (nice feature), but does not yet permit entry of other airline codes, as does TaxiDraw. There are several of these "other" airlines that utilize KPHL.

**Comment by BecOzIcan** [comment]
Agree

**Comment by wkitty42** [comment]
yes, absolutely agree... i forget which airport i was working on but i wanted to reserve parking for southwest airlines (SWA) but only SWK (i think) was listed and i had no way to add SWA...

**Comment by Portree-Kid** [comment]
Fixed in 0.0.19
