### ISSUE TITLE
DRAW UX: Drawing Tool not deactivated when mouse over / click icon

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#4]
Draw Tool 
Cclick start node
Move mouse. dashed line showed from first node to mouse : OK 
Mouse hover tool or any other clickable element 
Click on Parking Tool 

Observed : second node placed under parking tool icon, taxiway drawn between node 1 and 2, user still in drawing mode (to node 3) 

Expected : Click on active NAV/Tools takes priority and cancels drawing

**Comment by Portree-Kid** [comment]
Fixed
