### ISSUE TITLE
Return to Check Results after fixing an issue

### ISSUE THREAD

**Issue by LGBudd** [Portree-Kid/flightgear-airports#44]
It would be more efficient if focus was returned to the Check Result box after one  issue is fixed, at least until ALL issues are fixed. For example, if the Check Result box lists three overlapping parking positions and the first on the list is fixed, return to the list immediately so the other two overlapping positions can be fixed without unnecessary steps.

**Comment by wkitty42** [comment]
you cannot click on the check results (on the left) and return to that list?

personally, i've been saving and doing another check... sometimes fixing one thing will fix others...

**Comment by LGBudd** [comment]
That works. Saw the Properties box pop-up and didn't see the Check Result still available. I'll close this...:)
