### ISSUE TITLE
OpenStreetMap not loading

### ISSUE THREAD

**Issue by Honu4** [Portree-Kid/flightgear-airports#45]
This is just the top of the Console log. 

<img width="553" alt="Screen Shot 2020-07-09 at 1 53 08 PM" src="https://user-images.githubusercontent.com/67807217/87101754-9cc73e00-c1eb-11ea-9042-30f9ca74915b.png">

**Comment by LGBudd** [comment]
Got the same result when attempting to load a new airport (an airport I had not worked on before). The Open Street Map appears when working on the airport I have been working on the last few days.

**Comment by Honu4** [comment]
> The Open Street Map appears when working on the airport I have been working on the last few days.

I believe they're cached tiles

**Comment by Portree-Kid** [comment]
Fixed in 0.0.19
