### ISSUE TITLE
Add a check that connected pushback segments have an associated pushback holding point at the ending node 

### ISSUE THREAD

**Issue by LGBudd** [Portree-Kid/flightgear-airports#46]
Just a simple check to eliminate something that is easy to miss when working with a large groundnet.

**Comment by Portree-Kid** [comment]
I thought that would be caught by the check requiring a parking to be connected to a pushback hold node.

**Comment by LGBudd** [comment]
Sounds like that should do it but I can't say I've run up against that check. What is the error message? 
Separate but may be related: I have suspected that some pushback holding points may be lost when the file is saved, but need to check thoroughly when doing the next groundnet.

**Comment by LGBudd** [comment]
Here's a situation I just ran across. Missing pushback, Check Result looks fine.
![2020-07-10](https://user-images.githubusercontent.com/19491531/87171389-39471a00-c298-11ea-8927-a52707734497.png)

**Comment by Portree-Kid** [comment]
Thinking about it, it maybe a invisible pushback icon.

**Comment by Portree-Kid** [comment]
Bug :-( fixed in 0.0.20
