### ISSUE TITLE
Attempted upload produces error: Unknown Radius in parking

### ISSUE THREAD

**Issue by Honu4** [Portree-Kid/flightgear-airports#47]
In-app check is fine. When attempting to upload airport an error is produced and checklist is populated with "Unkown Radius" errors at parking positions and upload fails.
MacOS
<img width="577" alt="Screen Shot 2020-07-09 at 3 46 26 PM" src="https://user-images.githubusercontent.com/67807217/87107425-6ee9f580-c1fb-11ea-9eaf-0ed3df049c08.png">

**Comment by BecOzIcan** [comment]
Click on the target icon next to unknown radius and paste here a screenshot of the parkpos screen (if the radius looks ok)

**Comment by Honu4** [comment]
3 random spots. Not sure what's up with the taxiline node.

<img width="863" alt="Screen Shot 2020-07-10 at 11 37 06 PM" src="https://user-images.githubusercontent.com/67807217/87221264-4dc1fb80-c306-11ea-8a0a-d12edfcf9776.png">
<img width="943" alt="Screen Shot 2020-07-10 at 11 37 46 PM" src="https://user-images.githubusercontent.com/67807217/87221270-6205f880-c306-11ea-9059-59a2aa3aef5d.png">
<img width="1208" alt="Screen Shot 2020-07-10 at 11 38 43 PM" src="https://user-images.githubusercontent.com/67807217/87221288-8c57b600-c306-11ea-843c-084e196554f3.png">

**Comment by BecOzIcan** [comment]
S1 : No idea why a paropos error is returned for a node > Keith 

S2 : Aircrafts cannot pivot on their parkpos. Looks like you are entering parking through the nose ? 

Segments in and out of parkpos must hace the same heading 

See screenshot: Left hand side, if you leave the parkpos rolling forward, Right hand side if you leave the parkpospushing back (using the same route you used to get in) 

![image](https://user-images.githubusercontent.com/49523106/87221668-1cead080-c3b1-11ea-9d08-c810c6565641.png)

**Comment by BecOzIcan** [comment]
@Portree-Kid 

Error shown on third screenshot 3 by Honu4, are you testing segment heading vs parkpos heading ? Is this the error in your view? If yes, messaging should be "Parkpos route access not aligned"

Secreenshot 1 : totally confused :-)

**Comment by Honu4** [comment]
@BecOzIcan 
How are you getting the directional indicators on the taxilines?

**Comment by BecOzIcan** [comment]
Not sure, they appear automatically for me. maybe be a missing font/icon on the mac version

**Comment by BecOzIcan** [comment]
Confirming the error/bug. 

> v0.019
> Click Check Icon in RHS Panel (between Save and Bi Directional Icons)
> Get "Results" panel : Shows all ticked/OK  produces full validation 
![image](https://user-images.githubusercontent.com/49523106/87236875-c70a3d00-c431-11ea-8191-5579c51ef097.png)

> SAVE (RHS Panel Icon)
> UPLOAD (RHS Panel Icon Above Export) 

Returns 46 Unknown (and Immaterial) Radius Errors 

![image](https://user-images.githubusercontent.com/49523106/87236893-fe78e980-c431-11ea-9495-cc67b2fb836c.png)

**Comment by Portree-Kid** [comment]
Reason is, that the boxes are not visible. I see two ways forward. 

1. Boxes are visible in non edit mode.
2. Boxes are generated non visible. 

I'm for 1.

**Comment by BecOzIcan** [comment]
Sorry I don't understand the comment. What 'Boxes' are you referring to ? I should have kept both issues (taxiway marking and validation discrepancies) separate

**Comment by Portree-Kid** [comment]
They are connected. In edit view only parkings with known radii have the box. The others have a circle. The check can only do the exact overlap check with the parking box.

**Comment by BecOzIcan** [comment]
1. Happy with your recommendation of Boxes shown in Non Edit mode where radii is standard (preferably replace the circle)
2. Still an issues with discrepancies in checks originally reported by Honu:  there is no way I have 46 overlapping parkpos at VVNB, whatever the shape

![image](https://user-images.githubusercontent.com/49523106/87241009-0ea8bd00-c462-11ea-9c35-48ed049bd227.png)

![image](https://user-images.githubusercontent.com/49523106/87241016-15cfcb00-c462-11ea-9327-da670d1d67da.png)

**Comment by wkitty42** [comment]
> How are you getting the directional indicators on the taxilines?

i have the same question... mine are also red boxes on linux using the appimage...

**Comment by Portree-Kid** [comment]
Fixed in 0.0.20
