### ISSUE TITLE
Expose FGA Version to User more clearly

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#51]
Given the pace of releases it would be good to have an indication of what version the user is running to facilitate troubleshooting and regression. 

Somewhere in Help and or in Window Title Bar ?

![image](https://user-images.githubusercontent.com/49523106/87236327-43e5e880-c42b-11ea-9533-f7192a098814.png)

**Comment by Honu4** [comment]
It's on the lower right info bar on Mac

<img width="557" alt="Screen Shot 2020-07-11 at 3 19 29 PM" src="https://user-images.githubusercontent.com/67807217/87236890-50663480-c38a-11ea-85b7-5c9d68e0cb66.png">

**Comment by BecOzIcan** [comment]
Good Eye ! Found it in same place on Windows.

**Comment by Portree-Kid** [comment]
Fixed in 0.0.27
