### ISSUE TITLE
Cannot Change Export Folder Path

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#53]
> v0.019 Wint10
> Select a new folder for Export Directory

![image](https://user-images.githubusercontent.com/49523106/87236990-d094a480-c433-11ea-971a-cf3b48ff39c0.png)

> Settings Panel does not show the new path 
> Re Open Selection Button : New Path is Shown as in 'Select Folder" panel

**Comment by BecOzIcan** [comment]
And change is not effective either : Export triggered after change still go to the original folder

**Comment by Portree-Kid** [comment]
Fixed in 0.0.20
