### ISSUE TITLE
CHECK: Cannot See/Correct Properties of Overlapping Parking at fault

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#54]
v0.019 - WIN10

> Edit Mode / Run Check 
> See List of Overlapping ParkPos  
> Hit Target Icon to go to first Parking ? Parking Highlighted on map 
> Properties Panel does not show Selected Parking details. Cannot edit Radii (or any other property)
> Clicking on other element (Node) brings the relevant Properties Pan 
> Clicking on any Parkpos only brings the Airport General Properties panel 

![image](https://user-images.githubusercontent.com/49523106/87247840-8d6d1c80-c499-11ea-8fd7-cfff3f67a369.png)

![image](https://user-images.githubusercontent.com/49523106/87247889-d624d580-c499-11ea-9e7b-251519e6a8ad.png)

![image](https://user-images.githubusercontent.com/49523106/87247944-14ba9000-c49a-11ea-98af-361810fc90f7.png)

**Comment by Portree-Kid** [comment]
Please ReTest on v0.0.20

**Comment by BecOzIcan** [comment]
Re-tested in v0.020 : Still same (broken) behaviour.

**Comment by Portree-Kid** [comment]
Then it seemingly is an error in the ParkingEditScreen, that I am reworking because of #42

**Comment by BecOzIcan** [comment]
Panel re appears after running a check triggering a "name empty" error

**Comment by Portree-Kid** [comment]
Fixed in 0.0.21

**Comment by Portree-Kid** [comment]
Fixed in 0.0.21
