### ISSUE TITLE
parking restricted to certain airlines takes flightplan xml filename as airline in selection list

### ISSUE THREAD

**Issue by wkitty42** [Portree-Kid/flightgear-airports#55]
this is a bit disconcerting because the name of the file has nothing to do with the airlines that may be listed inside it... the airline names/indicators should be taken from the airline tag for each craft listed...

for example: i have AI/Traffic/misc/LandmarkAviation.xml... the airline tags in this file are all LMA... when i go to restrict the parking at KRDU where LMA is home-based, the list shows LandmarkAviation (the name of the file) instead of LMA (the abbreviation of the airline)...

while working with my GA craft, i have removed all other flightplans except the one with the few craft i want to test with... i copied LandmarkAviation.xml to (eg) LA-ERJ1.xml and stripped out all craft and flights except those for LA-ERJ1... when i went to look at the parking restriction list, it shows the airline as LA-ERJ1 instead of LMA...

one can also see this if they go to EHLE and look at the parking restrictions list... the GA flights there are in AI/Traffic/misc/WooningAviation.xml and the airline tag is "Wooning Aviation"...

**Comment by BecOzIcan** [comment]
@Portree-Kid 

Confirming airlinesCodes in <parking> tags of groundnets are matched to the <airline></airline>tag inside <aircraft></aircraft> entries in Traffic files and not the name of the traffic file itself.

Valid Prod Test Data if needed : 
Compass Airlines (File CPZ.xml) Updated OCT 019
Contains both <airline>AAL</airline>and <airline>DAL</airline> aircrafts 
as Compass operates flights for both airlines, under their respective  flights numbers

**Comment by Portree-Kid** [comment]
![image](https://user-images.githubusercontent.com/999932/87322542-d66eb080-c52d-11ea-84ba-29bf9db516ec.png)

This should be right, or?

**Comment by Portree-Kid** [comment]
Fixed in 0.0.21

**Comment by BecOzIcan** [comment]
Yep end user wouldn't see a difference anyway.
