### ISSUE TITLE
v0.20 - Upload : No Process Status or Result Confirmation

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#57]
- Upload from RHS Map Icon
- GPL Tick and User Details ok 
- Click OK 
> No information to user on progress after "Has Started" (Progress Bar or Spinning wheel)
> No information to user on upload completion (on upload Pop Up or on WIP Panel

**Comment by BecOzIcan** [comment]
Process did in fact complete (I got the PR) but regular user wouldn't know

**Comment by wkitty42** [comment]
i can confirm this and i've not seen my KCHS show up yet, either... i even went back and tried with 0.0.19 which gave me the bad radius thing... i could try with 0.0.17 back to 0.0.15 but...

**Comment by Portree-Kid** [comment]
Fixed 0.0.22
