### ISSUE TITLE
v0.20 - Route Validation from ParkPos to Runway Fail

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#58]
- FGA Validation returned no error
- Build Check returned route error 

![image](https://user-images.githubusercontent.com/49523106/87370054-51cf7100-c5c5-11ea-9bd6-3e7663c5d5d4.png)

**Comment by BecOzIcan** [comment]
Travis Error is Valid : Not Route Found from Parkpos to Node on Runway (was going against uni directional segment) 

Bug Name Changed

**Comment by Portree-Kid** [comment]
The check might be a wee bit funny. Since the node is now an End in one direction. 
![image](https://user-images.githubusercontent.com/999932/87678871-c3512000-c77b-11ea-9847-4829831b71a7.png)

**Comment by BecOzIcan** [comment]
Sorry, I don't understand what you are trying to say. The way I understand this test(s) :

LEGITIMATE Test : 
1. A node connected to a single segment is legitimate if marked as "on runway" and has passed the Turf Test. This makes it the **Route End, Runway side**
2. A node connected to a single segment is legitimate if it connects to a Parkpos. This makes it the **Route End, ParkPos side** 
3. From (1) A node connected ONLY to a single segment AND not marked as "On Runway" is Illegitimate
 
_note: the Turf test (on runway) needs to run before the illegitimate test so (1) has valid entry conditions_

NO ROUTE FOUND Test
I guess you only test pairs of Route end points from the above two definitions?

The Parkpos in Red on image has invalid configuration. Access route to a parkpos, if unique, should always be bidirectional. so you can get both in and out of it.

**Comment by BecOzIcan** [comment]
To make your test easier (all lower level elements valid), use VVNB and mark the single segment in red unidirectional RIGHT to LEFT

![image](https://user-images.githubusercontent.com/49523106/87684595-c5d86780-c7c5-11ea-8d5a-e9545c6c9b21.png)

**Comment by Portree-Kid** [comment]
> NO ROUTE FOUND Test
> I guess you only test pairs of Route end points from the above two definitions?

Correct Parking -> Runway and Runway -> Parking

> PARKPOS TEST (from the image)
> The existing parkpos test should run before the route tests, right ? Maybe it's only a case of test cases hierarchy. Individual elements validity should be tested before route ones and if individual elements tests fail, testing is interrupted (routes not tested)

* Correct Graph 
P --- 2 --- 3 --- R
* Two unconnected Nodes (4 and 3) above each other
P --- 2  --- (4|3) --- R
The case I'm trying to find with the LEGITIMATE Test 
* Unidirectional from 2 -> 3 (Case of screenshot)
P --- 2 >>> 3 --- R
ID 3 is semantically an end when viewed from the runway towards parking.

**Comment by BecOzIcan** [comment]
Ok I think I got it

For the case of screenshot, you cannot decide 3 is illegitimate during your node or parkpos test phase because 3's 'illegitimacy' exist only in the context of routing ie trying to get out of the parkpos. 

1. Test Node Legitimacy > 3 passes the test 
2. Test Parkpos Validity > 2 passes because the segment connected to parkpos is bidirectionnal
3. Test Routes > Fails because I cannot reach the parkpos from the runway

More over if I only add a new bidirectionnal route between 2 and another route without changing anything else. 3 is no longer illegitimate because I have an alternative route out.

That calls for differentiating / hierarchizing test between structural and contextual. 

Structural (illegitimate)
Nodes : Broken Routes ie Unconnected Node unless On Runway or Pushback Holding Point
ParkPos: Inaccessible Parking ie segments in/out of park pos not bidirectional (not threshold or route dependent)
Pushback: the usual 

Routing is contextual: 
Parking -> Runway and Runway -> Parking

**Comment by BecOzIcan** [comment]
Before I forget : you cannot identify 3 as the problem when checking the route because you could have other blockages further away in the same route which would also interrupt your test.
MVP expectation is only to signal the route is invalid. User has to check all segments to find the problem(s) with it. Does this help ?

**Comment by Portree-Kid** [comment]
While trying to sleep I also decided to split between a structural and routing graph. That was 3 passes the structural test and the routing test.

**Comment by BecOzIcan** [comment]
Damn You're up early!. Good Morning! 
The part I still don't get is my initial issues was only that Travis had it right and FGA didn't so I thought it was just a matter of re aligning them.

**Comment by Portree-Kid** [comment]
;-) yes just a matter of realignment. Maybe I'll extract the FG Airports check into groundweb. That way no pull request would ever be opened without a minimum quality.

**Comment by BecOzIcan** [comment]
We still use Groundweb/Azure to upload our historical TD files. These have much less checks in place so likely they will all end up rejected systematically. We should keep this "backdoor" open. Only impact is on me on the merging side and I am ok with it.

For as long as FGA and Travis checks align, all FGA uploads will meet quality requirements.

**Comment by BecOzIcan** [comment]
We can restrict groundweb once FGA stable

**Comment by Portree-Kid** [comment]
Fixed in 0.0.21
