### ISSUE TITLE
v0.20 - Nodes on Runway not Checked 

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#59]
Discrepancy between TD and FGA. 
TD detects multiple nodes on runway not marked as such in files created in FGA and submitted

**Comment by wkitty42** [comment]
is this saying that all nodes in a runway have to be marked as such? not just the final node on the runway?

**Comment by BecOzIcan** [comment]
Yes all nodes on runway should be marked as such.
Departing aircrafts will queue at the last "not on runway" node on hte route (ie just outside the runway from the rule above) until cleared to take off

**Comment by wkitty42** [comment]
ooooooohhhhh... ok, so my trick of having only one on the runway to grab landing craft with is in error... alright...

**Comment by Portree-Kid** [comment]
![image](https://user-images.githubusercontent.com/999932/87909532-b75daa80-ca68-11ea-9e30-4790103b1e04.png)
Works now, but may lead to problems. Scotland has lots of taxi down runway type of airports. AI doesn't handle them well "yet".

**Comment by BecOzIcan** [comment]
You mean backtracking? Like use the runway as taxiway all the way to the threshold and swing around? I just did a paragraph on them in the wiki last week with tips and trick from Brett. Awesome news for the Turf Test (love the name, keeping it)

**Comment by Portree-Kid** [comment]
Yes. Maybe Runway is not the correct check? More like Threshold path?

**Comment by BecOzIcan** [comment]
Yes. The best test would be node on the line between each pair of THR but we would need some tolerance around that, can you calculate a "Theoretical Runway Box" for node on runway test purposes : 
Length = distance between THR pair
Width = 15 meters (our smallest aircraft radius x2)
Position and Heading : Centered between THR

The European Aviation Safety Agency suggest 18 is the minimum real width. Ref Doc Link in the Wiki Radii page

![image](https://user-images.githubusercontent.com/49523106/87926789-8bbcdd80-cac5-11ea-87a5-f686b98e9a7c.png)

**Comment by Portree-Kid** [comment]
Fixed in 0.0.21
