### ISSUE TITLE
PARKPOS Selecting Parkpos via Heading Marker does NOT unselect previous element

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#6]
Pick a pack of parkos close to each other 

Click on the first parkpos Heading marker 
- Marker turn red (/)
- Parkpos radii highlighted in red (/)
- Parkpos anchor/center not highlighted (x) 
- Parkpos details in Properties Panel (/)

Click on another closeby parkpos Heading marker
- Heading Marker turn red (/)
- Heading Marker of FIRST PARKPOS remains red (x)
- Parkpos radii highlighted in red (/)
- Parkpos anchor/center not highlighted (x)  

Expectation 
1. Clicking on any particulars of an element highlight the entire element ie, for parkpos does not matter if selected via click on center marker, heading marker or radi, all three elements should be hgighlighted
2 Clicking away (on a different element) should de-select all 3 elements of the parkpos

**Comment by Portree-Kid** [comment]
Fixed
