### ISSUE TITLE
v0.26 - Layer Toggles (APT, Threshold) no longer work

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#61]

**Comment by wkitty42** [comment]
i had to play with them... found if you toggle them in view mode the first time you load, they will then toggle in both view and edit modes through that session...

**Comment by Portree-Kid** [comment]
Works for me

**Comment by BecOzIcan** [comment]
Issue still exist in 0.0.26. Toggling APT Off has effect only if first action on startup and does not "stick"

1. Start FGA 
2. Toggle APT off. APT elements removed from map 
3. Search / Select / Navigate to Airport 
4. Observe APT Toggle UI : APT OFF. 
5. Observe APT Elements on map (yellow lines) : SHOWN 
6. Try to toggle APT on/off in UI : Inactive 

![image](https://user-images.githubusercontent.com/49523106/97067857-f114f300-160d-11eb-9368-cbe8eff70326.png)

**Comment by Portree-Kid** [comment]
Fixed in 0.0.27
