### ISSUE TITLE
v0.20 Segments Midpoints Cannot be used to anchor/connect if activated while drawing route

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#64]
Will leverage the inactive midpoint to anchor a pushback route on the northern part 

![image](https://user-images.githubusercontent.com/49523106/87526531-4d42af80-c6ce-11ea-920d-8b983506b009.png)

> Pushback tool, First click on parkpos
> Second click (drawing mode) on midpoint to 'activate' it 
> Midpoint created (new midpoints on both sides)
> Mouse hover show hand (can finish anchor here) 
> Clicking on new mode, route not anchored to it . impossible to select newly activated node to finish or continue the route. Need to exit as 'stuck' in drawing mode (Save/Re Edit)
 

![image](https://user-images.githubusercontent.com/49523106/87526956-cf32d880-c6ce-11ea-8f99-e8ff7c62f14a.png)

Expected : Nodes created by 'activating a midpoint on the fly' behave like any normal active node and can be added to a route

**Comment by wkitty42** [comment]
i can confirm this... i've gotten to used to the edit/save/edit work flow that i haven't even thought about filing an issue about it :disappointed:

**Comment by Portree-Kid** [comment]
Fixed in 0.0.25
