### ISSUE TITLE
v0.20 - Only Certain Unidirectional markers showed on zoom out 

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#66]
Some restriction in rendering I guess: size of segment vs size of icon.
TD always show the marker but messy UI. 

![image](https://user-images.githubusercontent.com/49523106/87530389-9e08d700-c6d3-11ea-9489-6b28b428970a.png)

![image](https://user-images.githubusercontent.com/49523106/87530492-bd9fff80-c6d3-11ea-820e-b8f5a9d0b94f.png)

![image](https://user-images.githubusercontent.com/49523106/87530849-4323af80-c6d4-11ea-8005-6dd33153cb55.png)

![image](https://user-images.githubusercontent.com/49523106/87530896-5171cb80-c6d4-11ea-84ea-3e3bb4ee3963.png)

**Comment by Portree-Kid** [comment]
Fixed in 0.0.27
