### ISSUE TITLE
Check Pushback Holding Point : Test Conditions

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#69]
Tests for each single Pushback Holding Point (PHP)

The PHP IS connected to at least one Pushback Route Segment (no maximum) 
Error Message "Pushback Holding Point not Connected to Pushback Route"

The PHP Each Pushback Holding Point IS NOT connected to more than one Bidirectional segment
Error Message "Too many Taxi routes from Pushback Holding Point"

The PHP IS NOT connected to any Uni Directional segment
Error Message "Pushback Holding Point Exit route is not bidirectional"

**Comment by Portree-Kid** [comment]
"PUSHBACK_NOT_CONNECTED": ["Pushback Holding Point not Connected to Pushback Route", ""],
    "TO_MANY_PUSHBACK_ROUTES": ["Too many Taxi routes from Pushback Holding Point", ""],
    "PUSHBACK_EXIT_NOT_BIDRECTIONAL": ["Pushback Holding Point Exit route is not bidirectional", ""]

An alternative long description can be added now. It's shown on mouse over

**Comment by Portree-Kid** [comment]
Done in 0.0.22
