### ISSUE TITLE
SELECT Cannot Extend Selection with Shift-Click

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#7]
SHIFT-CLICK

- Should allow me to select more than one element of a common type (3 Parkpos OR 2 sgments) and apply changes to all elements at once 
- Properties should reflect common elements and blank uniques ones eg selectin Gate A1 A2 and A3 the properies name is A (common) but number is blank (unique per element) 

Any change to a value in the property panel should apply to all selected elements 

Uses Case : 
Set a common heading and or radius for a cluster of Parpos 
Turning a complete route (multiple segments) from Pushback to Normal at once 
Turning a complete route (multiple segments) from Unidirectional to bidirectional or changing from forward to backward

**Comment by Portree-Kid** [comment]
Part one fixed
I'll add a second issue
https://github.com/Portree-Kid/flightgear-airports/issues/40
