### ISSUE TITLE
Check: Angle between last pushback segment and bidirectional segment is less than 100 degrees

### ISSUE THREAD

**Issue by LGBudd** [Portree-Kid/flightgear-airports#70]
The angle formed by the last pushback segment (with endpoint a pushback holding point) and the bidirectional segment connected to it must be less than 100 degrees for pushbacks and sometimes departures to work as expected. 
Error message might read: "Angle between pushback and bidirectional segments must be < 100 degrees"

**Comment by BecOzIcan** [comment]
Is this from the traffic manager code ? In my experience its more the opposite ie the angle must be > 90 ie an L shape would work but a V shape would not. Am IO misreading this ?

**Comment by wkitty42** [comment]
what if the pushback connects to a one-way segment?

**Comment by LGBudd** [comment]
It's not from the traffic manager code. I first tried this after reading the following:

> Pushback routes that turn more than approximately 100% from one node can cause all the pushbacks to fail, for me this has also been the cause for aircraft stopping at the runway and not taking off, why this would be I have no idea but correcting the offending pushback usually corrects the problem.
from this link: [(https://forum.flightgear.org/viewtopic.php?f=23&t=30116&p=312203&hilit=100%25#p312203)]
I interpreted the "100%" to actually mean "100 degrees" and it has worked for me (and behaved as described) as shown in this screenshot as angle "2":
![Angle LT 100 deg](https://user-images.githubusercontent.com/19491531/87855308-02e34d80-c8dd-11ea-9225-84d34187d7f3.jpg)

I have never tried a one-way segment with a pushback, so I don't know what the effect would be.

**Comment by BecOzIcan** [comment]
I see. Much clearer.
The angle we are talking about is the on the the left of you #2) ie the angle between the segment out of parkpos and the one leading to pushback holding point (the two pin segments) 
Angle #2 does not matter because aircrafts always roll forward straight out of pushback holding points

**Comment by BecOzIcan** [comment]
Gooneybird and I are running extra testing on pushbacks right now so no rules to implement yet for FGA. aside from pushback routes must be bidirectional and align (same heading) with parkpos). Extra validation/tests if needed will be set once testing complete.

**Comment by LGBudd** [comment]
Closed
