### ISSUE TITLE
0.20 freezes on viewing apt.dat

### ISSUE THREAD

**Issue by gooneybird47** [Portree-Kid/flightgear-airports#71]
0.20 freezes with white screen and "busy circle" when apt.dat comes into view.

![fga-21](https://user-images.githubusercontent.com/67790879/87775993-eb458f80-c81e-11ea-8dc1-4274b11f17c8.jpg)

This happens with a clean install and installed over earlier version. Also tested on a laptop with the same result.

**Comment by Portree-Kid** [comment]
Which airport is that?

**Comment by gooneybird47** [comment]
EGSH but It happens at all airports with or without groundnets as soon as the apt.dat layers appears. FG 2020.1.2 and win 10.  
I was beginning to think it was something running on my computer that was interfering with FGA but I set up the same data on my laptop with the same result.

**Comment by Portree-Kid** [comment]
Fixed in 0.0.21
