### ISSUE TITLE
v0.20 - Route Drawn as Pushback Stays Pink when toggled back to regular on the fly

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#72]
Draw new Pushback route 

![image](https://user-images.githubusercontent.com/49523106/87776976-ff63ae00-c86b-11ea-8e15-ce0cd1f278e4.png)
![image](https://user-images.githubusercontent.com/49523106/87776998-0985ac80-c86c-11ea-964b-4e56eb949f52.png)

Select and Toggle PushBack Off in Propertiers 

![image](https://user-images.githubusercontent.com/49523106/87777056-2a4e0200-c86c-11ea-8f66-25e9f27fb805.png)

Select another point elsewhere and observe the route > Still showed in Pink 
Re select the route and check properties > Not a Pushback 
> SAVE/RE EDIT : Route rendered properly 

![image](https://user-images.githubusercontent.com/49523106/87777190-64b79f00-c86c-11ea-87df-5842d8de5dd7.png)

**Comment by Portree-Kid** [comment]
Fixed in 0.0.22
