### ISSUE TITLE
v0.20 [DEL] is not a keyboard shortcut for the Bin/Trash icon 

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#73]
The ONE thing driving me crazy and slowly destroying my keyboard as I repeatedly hit it with no effect whatsoever

IF Element selected (Node, Segment, Parkpos) > hitting DEL should delete it 
IF No Element Selected > Hitting DEL should only destroy my keyboard further

**Comment by Portree-Kid** [comment]
Done in 0.0.22
