### ISSUE TITLE
v0.20 Nodes move on save as Lat Lon are persisted in XML rounded to 3 decimals instead of 6.  

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#75]
ENTERED in FGA 

![image](https://user-images.githubusercontent.com/49523106/87781802-ba904500-c874-11ea-97a2-fc89f4fb90eb.png)

EXPECTED in XML 

![image](https://user-images.githubusercontent.com/49523106/87781896-da276d80-c874-11ea-957b-f14ee8a8379b.png)

OBSERVED in XML 

![image](https://user-images.githubusercontent.com/49523106/87782190-6b96df80-c875-11ea-8c50-84bfcfc5eef1.png)

SAVE / EDIT 

Point has moved 

![image](https://user-images.githubusercontent.com/49523106/87782028-1c50af00-c875-11ea-9cb6-5d2e09cea524.png)

Previous bug was about the UI rendering #18  but it looks like the data is not persisted properly. Is there a limitation in hte XML scheme or in traffic manager to read the XML with 6 decimals ?

**Comment by BecOzIcan** [comment]
I will have a quick chat to James to verify if 6 digits are likely to cause an issue downstream, in traffic manager

**Comment by BecOzIcan** [comment]
Confirmed with James that traffic manager would accept 6 decimals with no impact

**Comment by Portree-Kid** [comment]
Actually we have D.d with 6 decimals which would be 5 in D M.m.
https://wiki.openstreetmap.org/wiki/Precision_of_coordinates

**Comment by BecOzIcan** [comment]
Honestly struggling now

Precision of values we enter in FGA in Digtal Degrees with 6 decimals (DD.dddddd) is 0.11 meters from the OSM doco. The only reference to Decimal Minutes I see is the below table which tells me I need only 4 decimals in the Decimal Minutes D MM format to get a similar precision of 0.18 meters.

![image](https://user-images.githubusercontent.com/49523106/87798383-4911c000-c88f-11ea-8712-6408478acf04.png)

I have just ran an extra test on my sheet which confirms the same ie 4 decimals should be enough 

![image](https://user-images.githubusercontent.com/49523106/87799846-0cdf5f00-c891-11ea-9304-6dd1b198c0a4.png)

I guess at the end of the day the acid test for us is "the value I enter in FGA is the one I get back for the same point after I save and reload".

**Comment by BecOzIcan** [comment]
I am happy to let go on some UX/UI requirements if you can get this one across the MVP. We have suffered enough from the issue in Taxidraw to not want to repeat it in FGA. Name your price !

**Comment by sfrsfrsfr** [comment]
i don't have much to add except a 'me too'.

**Comment by Portree-Kid** [comment]
Fixed in 0.27

**Comment by sfrsfrsfr** [comment]
that's simply great!

**Comment by BecOzIcan** [comment]
Awesome news ! Feels like a second Christmas morning. Thanks a lot Keith. Looking forward to this release
