### ISSUE TITLE
node and line index numbers

### ISSUE THREAD

**Issue by wkitty42** [Portree-Kid/flightgear-airports#76]
please display the node and/or line index numbers on the property data tab... this way when travis tells us about a problem, we can do to the index he points us to... FGA finds it for you but knowing what the index number is would be helpful when needed...

**Comment by BecOzIcan** [comment]
Not MVP. 
- Regular End users should not have to go through the trouble of reading a Travis report to understand an issue.
- Currently (WIP) FGA checks replicate the Travis tests with a nicer interface and navigates the user to the specific issue, in FGA
- No need to expose the raw data in this context

**Comment by wkitty42** [comment]
don't know what "MVP" means in this context...

i agree that end users should not have to go find index 23 and index 47 in their raw groundnet.xml file so they can find out what parking place is being talked about in the instance of overlapping parking... perhaps i should have requested that travis list the parking names instead?

but there are times that knowing the index of whatever is being complained about would be nice to know just in case someone wants/needs to go rummaging through the raw data file...

**Comment by Portree-Kid** [comment]
MVP is Minimum Viable Product. For FGA this defines the point where FGA completely can replace Taxidraw 100%. That is goal 1. Then the bells & whistles.

**Comment by Portree-Kid** [comment]
Need that for AI testdata
