### ISSUE TITLE
v0.20 UI Properties Panel ACT D marked as size (27) instead of (26)

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#78]
Radius of ACT D is 26 
> Property saved correctly as 26 in XML 
> But marked incorrectly as 27 in UI Panel

![image](https://user-images.githubusercontent.com/49523106/87870603-0534cd00-c9ed-11ea-8128-98c05d37e240.png)

**Comment by Portree-Kid** [comment]
Fixed in 0.0.21
