### ISSUE TITLE
v0.021 - UI - Settings - Airport Directory path not shown (but valid) 

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#81]
Can select, Can scan but can't see the path. Confusing to first time users.

Also copy for Traffic directory and APT file no longer needed (or are they not showing either maybe) 

![image](https://user-images.githubusercontent.com/49523106/88459844-869fca00-cedb-11ea-8d5a-02a88f44bab3.png)

**Comment by Portree-Kid** [comment]
Can't reproduce. Are there messages in the debug console?

**Comment by BecOzIcan** [comment]
Looks like they show up on restarting the program so issue only on initial set up. Closing for now, Will check if same in next release.
