### ISSUE TITLE
v0.21 - Inconsistent Node on Runway Validation - Check vs Upload

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#82]
> Edit Mode, Check Groundnet from RHS panel Icon : No Errors Found 

![image](https://user-images.githubusercontent.com/49523106/88469110-c8a72b00-cf30-11ea-901a-ad6d2eb2a0cb.png)

> Save, Upload, 
> Upload Rejected 27 errors found. All for nodes on runway 

![image](https://user-images.githubusercontent.com/49523106/88469102-a7ded580-cf30-11ea-89c3-855258d60d6a.png)

**Comment by Portree-Kid** [comment]
Fixed in 0.0.22
