### ISSUE TITLE
V0.21 - Upload Icon in WIP Panel non functional 

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#83]
Clicking on icon does nothing.
No message to user on any issue 

![image](https://user-images.githubusercontent.com/49523106/88469146-5125cb80-cf31-11ea-96b0-11d25fceb274.png)

**Comment by wkitty42** [comment]
i spoke of this one in like .17 or .18 but not as an individual issue...

**Comment by Portree-Kid** [comment]
Fixed in 0.0.22
