### ISSUE TITLE
Typo in 0.0.21 ?

### ISSUE THREAD

**Issue by gooneybird47** [Portree-Kid/flightgear-airports#84]
I'm getting a warning about "Lookup undefinded" in renderer.js:11 I'm assuming this is a typo and should "undefined" . Don't know how to edit that this end.

I'm still having the same issues as #71 could this be causing that.

**Comment by Portree-Kid** [comment]
That just is a warning for the time being. Happens when clicking on parking when not in edit mode. Typo fixed in 0.0.22.
