### ISSUE TITLE
Maintain a color while node is being moved

### ISSUE THREAD

**Issue by LGBudd** [Portree-Kid/flightgear-airports#85]
It would be helpful to assign a color to a node being moved by changing coordinates to make it easy to distinguish the node being moved from all others. Currently, as soon as a coordinate digit is input, the node goes white, like all other nodes. It is difficult (at least for one of us) to follow which node is being moved to see where it ends up.

**Comment by Portree-Kid** [comment]
Fixed in 0.0.22
