### ISSUE TITLE
0.0.21 Incorrect "Non Runwaynode on runway" error

### ISSUE THREAD

**Issue by Honu4** [Portree-Kid/flightgear-airports#86]
When running the check on a couple of groundnets, I'm getting a lot of `Non Runwaynode on runway` on nodes that are not on runways. Some of those nodes are on Parkpos nodes.
![Screen Shot 2020-08-01 at 7 21 08  #AM](https://user-images.githubusercontent.com/67807217/89106709-d55fcf00-d3c7-11ea-978a-23955b89ce63.png)
[PHOG.groundnet.xml.zip](https://github.com/Portree-Kid/flightgear-airports/files/5010992/PHOG.groundnet.xml.zip)
[PHNL.groundnet.xml.zip](https://github.com/Portree-Kid/flightgear-airports/files/5010994/PHNL.groundnet.xml.zip)
Groundnet files are ones I'm working on but have not submitted for update

MacOS 10.15.6

**Comment by Portree-Kid** [comment]
Fixed in 0.0.23

**Comment by Portree-Kid** [comment]
Fixed in 0.0.23 Some taxiways were runways.
