### ISSUE TITLE
0.0.22.appimage crash checking groundnet

### ISSUE THREAD

**Issue by wkitty42** [Portree-Kid/flightgear-airports#87]
i downloaded the 0.0.22 appimage, made it executable, and executed it... it opened at my KRDU groundnet... clicked edit and then check... got this in return...
![20200801-FGA-0-0-22-appimage-check-groundnet-crash-01](https://user-images.githubusercontent.com/4641713/89108675-41fabe00-d408-11ea-995e-d619c608ba1a.jpg)

**Comment by Honu4** [comment]
Also .DMG version
![Screen Shot 2020-08-01 at 9 10 07 AM](https://user-images.githubusercontent.com/67807217/89108786-f67bec00-d3d6-11ea-945f-f93df922c78d.png)

**Comment by Portree-Kid** [comment]
Fixed in 0.0.23
