### ISSUE TITLE
v0.0.23 - Spinning Wheel in White Box Covers Top Left of Screen

### ISSUE THREAD

**Issue by LGBudd** [Portree-Kid/flightgear-airports#88]
Upgraded to v0.0.23 and get the screen below. It appears everything is functioning except I can't seem to get rid of the white box with the spinning wheel. I can get into edit mode and make changes.
![2020-08-03](https://user-images.githubusercontent.com/19491531/89189914-4dfc9200-d566-11ea-8e72-79a4f461f5e3.png)
 
`Error message 1: Failed to load resource: net::ERR_CONNECTION_REFUSED localhost:8080/json/ai/models?d=99:11311
`
Many "objects" listed, then a Warning:

```
  | editedParkings | @ | renderer.js:11
-- | -- | -- | --
```
Then another error message:
`Uncaught Error: ENOENT: no such file or directory, open 'L:\FlightGear 2019.2.0\data\Airports\apt.dat.gz'  events.js:180`

This last error references the FlightGear version I had been using when I first scanned with FGA. I am actually using 2020.2.0 now and intend to upgrade to 2020.2.1 soon. Not sure how to proceed.

**Comment by Portree-Kid** [comment]
Oh dear I messed that up. The pavement layer can't load because the apt.dat doesn't exist anymore.

**Comment by Portree-Kid** [comment]
Fixed in 0,0.24

**Comment by LGBudd** [comment]
Thank you for fixing what I didn't even know existed...(pavement layer)...this program is really getting good!

**Comment by Portree-Kid** [comment]
Yes. Airports in the apt.dat can differ greatly from osm and who wants AI taxiing across grass.
