### ISSUE TITLE
PARKPOS Varying radii/Heading on map does not vary it in properties

### ISSUE THREAD

**Issue by BecOzIcan** [Portree-Kid/flightgear-airports#9]
Select/Highlight a Parkpos
Click/Grab the Heading/Radii Marker 
Vary the radii 

- Radii Visual (Bubble) size skip between preset discrete values (Categories A B C D E F)  (/) 
- Properties panel does not reflect radius changes made on the map (x) 
- Properties panel does not reflect heading changes made on the map (x) 

Expected : Changes made on the map are immediatly reflected in properties and vice versa

**Comment by Portree-Kid** [comment]
Fixed

**Comment by BecOzIcan** [comment]
Issue Re Introduced in V0.20

**Comment by Portree-Kid** [comment]
Works for me please retest in 0.0.21

**Comment by BecOzIcan** [comment]
Miscommunication. Values in properties panel updated only on releasing the handle
