### ISSUE TITLE
Manual setup of subdirectories

### ISSUE THREAD

**Issue by Portree-Kid** [Portree-Kid/flightgear-airports#91]
Currently the apt.dat and traffic subdirectories are "guessed" based on the FG directory. This fails on Linux and the user might want to set another one.

**Comment by Honu4** [comment]
Will this enhancement take care of #29 ?

**Comment by Portree-Kid** [comment]
Not directly. I  have a different solution. But #29 will be fixed in next version

**Comment by Portree-Kid** [comment]
Slightly differently solved. Now FGData must be set directly
