### ISSUE TITLE
Add ability to input Clearance Delivery, ATIS, and Detailed Approach and Departure Labels (v.0.0.24)

### ISSUE THREAD

**Issue by LGBudd** [Portree-Kid/flightgear-airports#92]
Add ability to input a Clearance Delivery and ATIS frequency, and add such labels as "Approach-North", "Departure-South" etc. to Frequencies.

**Comment by Portree-Kid** [comment]
Afair these are not actually supported and wouldn't have a meaning in FG

**Comment by wkitty42** [comment]
true at this time... i wonder, though, if having them in the groundnets would make them easier to fix/update instead of pulling them from apt.dat... but well, yeah... splitting the data into more places might not be a GoodThing<tm>...

**Comment by LGBudd** [comment]
OK, I was thinking they were used by ATC communications add-ons, such as RedGriffin ATC and RLeibner's ATC, since TaxiDraw allows for their input. There must be a different place where this same data is stored, eh?

**Comment by wkitty42** [comment]
these freqs are currently stored in the apt.dat...

i have been adding them to my groundnets but i guess if we're not going to do that any more, they'll be cut out automatically or we'll have to remove them from the ones that might be published with them...
