### ISSUE TITLE
Change in Parking Position Properties "Name" Deletes Parking Position (v0.0.24)

### ISSUE THREAD

**Issue by LGBudd** [Portree-Kid/flightgear-airports#93]
If part of the Parking Position Gate "Name" is changed by highlighting a part of the Name deleting it using the DELETE key, the entire parking position is deleted. For example, if a Parking Position is named "Gate_B36" and the "36" is highlighted and the DELETE key pressed, the parking position will be deleted.

**Comment by LGBudd** [comment]
This is also true if Coordinates are changed in the same way.

**Comment by Portree-Kid** [comment]
Fixed in 0.0.26
