### ISSUE TITLE
Deletion of End Node OR Entire End Segment Results in Return of Same Node/Segment After Save (V0.0.24)

### ISSUE THREAD

**Issue by LGBudd** [Portree-Kid/flightgear-airports#94]
Run check. In response to Error  "Node not a legitimate end", delete either the end node or the ending segment to eliminate the end that is not legitimate. A click on the error message in the same "Check" focuses on the area of the deleted node/segment, but the deleted node/segment is not displayed. Now do a "Save". Click "Check". (Can also Close the app, reopen and click "Check with same results). If the app was not closed, the same area is in focus and the deleted node/segment reappears.
Attached is the file (KDEN).

[KDEN.groundnet.zip](https://github.com/Portree-Kid/flightgear-airports/files/5165619/KDEN.groundnet.zip)

**Comment by LGBudd** [comment]
Have since found out from @BecOzlcan that entire segments are to be deleted, not end points. However, maybe a message could pop-up letting the user know how to do a proper delete or deletion of a point is made impossible without the associated segment being deleted? (Something that will help let a user know what is the correct way to delete).

**Comment by Portree-Kid** [comment]
Not reproducible in 0.0.25
